fix #2847 Orthogonalize direction matrix before rendering
OHIF/react-vtkjs-viewport pull request #171
Opened 2022-09-21 16:59 UTC by GitanjaliChhetri

2022-09-21 21:20 UTC, pieper requested changes
Does the MPR mode work if you just orthogonalize without clamping the image orientation?

2022-09-21 21:20 UTC, pieper commented on src/lib/getImageData.js
> +const iopTolerance = 0.01;
I don't know for sure what the OHIF convention would be here, but I would either spell out ImageOrientationPatient or at least include a comment that spells it out.

2022-09-21 21:20 UTC, pieper commented on src/lib/getImageData.js
> +  //correct for the 32bit float header issue before orthogonalizing
Here I would include a link to the github issue or other discussions so that future developer will know why this exists.

2022-09-21 21:20 UTC, pieper commented on src/lib/getImageData.js
> +const iopTolerance = 0.01;
But also as I said in the other email chain I would prefer we didn't have a hard cutoff for this.  If my calculation is right that's about half a degree and it could be significant.

2022-09-21 21:20 UTC, pieper commented on src/lib/getImageData.js
> +  //correct for the 32bit float header issue before orthogonalizing
Developers could track back to the github commit, but it's better to have some direct information in the code.

2022-09-21 23:22 UTC, GitanjaliChhetri commented on src/lib/getImageData.js
> +const iopTolerance = 0.01;
Sure, I will add a comment for ImageOrientationPatient. OHIF uses iop, ipp etc..
For the tolerance, how about setting it to 10^(-scale of the largest vector component) ?

2022-09-21 23:28 UTC, GitanjaliChhetri commented on src/lib/getImageData.js
> +  //correct for the 32bit float header issue before orthogonalizing
Sure, will include that link.

2022-09-22 08:55 UTC, Punzo commented on src/lib/getImageData.js
> +const iopTolerance = 0.01;
if we don't need any cutoff for the rotations, we could just cut the rounding errors. For a 32 bit number we can represent up to 7 digits of precision, so I propose a 1.e-6 for the tolerance.

2022-09-22 08:56 UTC, Punzo approved these changes

2022-09-22 09:00 UTC, Punzo commented
@GitanjaliChhetri please remember to link in PRs the original issue  from OHIF repo, i.e. https://github.com/OHIF/Viewers/issues/2847

2022-09-22 11:19 UTC, pieper commented on src/lib/getImageData.js
> +const iopTolerance = 0.01;
I guess for now setting the tolerance to a value that works for the cases we know about is the best option.  If we find more cases that don't render correctly we can revisit.  Thanks!

2022-09-26 13:04 UTC, merged